version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=sample_database_name
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST=127.0.0.1
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data

  web:
    build: .
    restart: on-failure
    volumes:
      - .:/code
    command: bash -c "python manage.py makemigrations sample_app --noinput && python manage.py migrate --noinput && python3 manage.py runserver 0.0.0.0:8000 --settings=django_docker_setup.settings_local"
    ports:
      - "8000:8000"
    depends_on:
      - db