# Generated by Django 3.0.5 on 2020-05-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_babel', models.CharField(max_length=180)),
                ('langue_babel', models.CharField(default='-', max_length=3)),
            ],
        ),
    ]
