# Generated by Django 3.0.5 on 2020-05-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='langue_babel',
            field=models.CharField(max_length=3),
        ),
    ]
