# Generated by Django 3.0.5 on 2020-05-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0003_auto_20200504_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrangeDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_date', models.CharField(max_length=180)),
                ('dim_date', models.CharField(blank=True, max_length=10)),
                ('text_date', models.CharField(blank=True, max_length=180)),
                ('value_date', models.CharField(blank=True, max_length=180)),
                ('color_date', models.CharField(blank=True, max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
