# Generated by Django 3.0.5 on 2020-05-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0004_orangedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='orangedb',
            name='output_date',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
