# Generated by Django 3.0.5 on 2020-05-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0005_orangedb_output_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_rasa', models.CharField(max_length=180)),
                ('intent_rasa', models.CharField(blank=True, max_length=10)),
                ('confidence_rasa', models.CharField(blank=True, max_length=180)),
                ('entity_rasa', models.CharField(blank=True, max_length=180)),
                ('ranking_rasa', models.CharField(blank=True, max_length=10)),
                ('output_date', models.CharField(blank=True, max_length=5000)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
