# Generated by Django 3.0.5 on 2020-05-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0007_auto_20200521_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='YellowDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_ortho', models.CharField(max_length=180)),
                ('output_ortho', models.CharField(blank=True, max_length=5000)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='reddb',
            old_name='output_date',
            new_name='output_rasa',
        ),
    ]
