# Generated by Django 3.0.5 on 2020-05-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0008_auto_20200524_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinkDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_feel', models.CharField(max_length=180)),
                ('output_feel', models.CharField(blank=True, max_length=5000)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
