# Generated by Django 3.0.5 on 2020-05-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0010_bluedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluedb',
            name='message_mar',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='orangedb',
            name='message_date',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pinkdb',
            name='message_feel',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reddb',
            name='message_rasa',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='task',
            name='message_babel',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='yellowdb',
            name='message_ortho',
            field=models.CharField(max_length=1000),
        ),
    ]
