# Generated by Django 3.0.5 on 2020-05-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0011_auto_20200528_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_lieux', models.CharField(max_length=1000)),
                ('output_lieux', models.CharField(blank=True, max_length=5000)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
